sudo: required
services:
 - docker

before_install:
 - docker build -t gogajr/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true gogajr/react-test npm test

after_success:
 - docker build -t gogajr/multi-client ./client
 - docker build -t gogajr/multi-nginx ./nginx
 - docker build -t gogajr/multi-server ./server
 - docker build -t gogajr/multi-worker ./worker